### ISSUE TITLE
这个橙狐支持MIUI的OTA吗？

### ISSUE THREAD

**Issue by yokinanya** [ymdzq/OFRP-device_xiaomi_mondrian#3]
就问问支不支持OTA，因为并没有在设置里面看到OTA的相关选项。
如果不支持的话，有没有增加OTA支持的计划？

**Comment by ymdzq** [comment]
不支持OTA，vab机型的ota更新是直接在系统中进行的，不经过recovery，所以没有相关功能。
twrp、橙狐功能的更新主要依赖国外开发者提供的开源代码，我个人没有开发相关功能的计划和能力。

另外说一句，ota的原理在于miui开发者比较miui每个文件的数据，前后两个版本之间的不同，生成一个体积小的补丁推送给用户，对用户手机里的旧版本文件打补丁进行升级，而如果要打补丁的文件被修改过则会升级失败。
miui每次更新都一定会刷boot分区的版本号，并且每次开机的时候会将boot分区打补丁得到的官方rec覆盖recovery分区，所以如果要保留第三方rec，就一定会修改miui的原文件，与ota原理冲突，导致ota失败，root也是同理，magisk和ksu会修改boot分区，与ota冲突
