### ISSUE TITLE
打扰下大佬，来询问下设备树的问题

### ISSUE THREAD

**Issue by chilan666** [ymdzq/OFRP-device_xiaomi_mondrian#6]
大佬做的设备树的commit很有学习价值
我是给小米Civi 1S适配twrp，改编了红米Note 12 Pro极速版的设备树，但是发现电量显示一直是100+（无论是编译twrp还是橙狐，电量显示都是100+）

原设备树地址：https://github.com/brigudav/android_device_xiaomi_redwood_twrp
我改编的地址：https://github.com/chilan666/android_device_xiaomi_zijin-twrp

我还试过移植米系的其它相同处理器的机型的twrp，问题也一样

我只在原来设备树的基础上加了一些内核模块，还有震动需要的bin文件，其他的文件都没改
是要用手机里提取出的文件替换原设备树里的文件吗

大佬如果没空解答的话也没关系，如果有时间解答的话我就不胜感激了
非常感谢！

**Comment by ymdzq** [comment]
我好像没有特别改过电量有关的代码，应该就是内核模块的问题，
内核模块要全用本机的，像k60我是解包官方rec把里面的ko拿出来直接用，
你用红米的肯定不行。

只要放官方rec里面那几个就够了，rec里放多了他也不会加载，
它是按TW_LOAD_VENDOR_MODULES你写的文件名优先从vendor_boot分区加载模块。

bin文件反而是没有那么多名堂，同平台的机器几乎都可以通用

**Comment by chilan666** [comment]
ok，我这就改一下，非常感谢大佬解答！
